Multiplay
extreal-dev/Extreal.Integration.Multiplay.Messaging pull request #2
Opened 2023-12-18 02:30 UTC by mahaweilu

# 何の変更を加えましたか？

# 何を確認しましたか?

## 実装

- [ ] Frameworkの誤った使い方にすぐに気づけるように、無効な引数や無効なメソッド呼び出しに対するチェックが入っていることを確認しました
- [ ] Framework実行時の動きが分かるように、ログ（Error/Warn/Info/Debug）を出力していることを確認しました
- [ ] 静的解析で問題が見つからないことを確認しました
- [ ] フレームワーク利用者が使うAPI（主にprivate以外）に C# ドキュメントを記述しました

## テスト

- [ ] 全ての自動テストが成功することを確認しました
- [ ] テストカバレッジが100%になることを確認しました
- [ ] サンプルがあるものはサンプルが動作することを確認しました

## 変更影響

- [ ] GuideのReleaseページに変更内容が追加されることを確認しました
- [ ] GuideのModuleページ（機能ページ）に変更が反映されることを確認しました
- [ ] GuideのLearningページに変更が反映されることを確認しました
- [ ] Sample Applicationに変更が反映されることを確認しました

# レビュアーへのメッセージ

2023-12-27 09:04 UTC, sus-yoshikane-t requested changes

2023-12-27 09:04 UTC, sus-yoshikane-t commented on Runtime/Extreal.Integration.Multiplay.Common.asmdef
> +        "Extreal.SampleApp.Holiday.Analyzer",
こちら残っていてよいのでしょうか？

2023-12-27 09:04 UTC, sus-yoshikane-t commented on Runtime/MultiplayClient.cs
> +                if ((objectToBeUpdated.transform.position - networkObjectInfo.Position).sqrMagnitude > 0f)
Rotationのみ変化したオブジェクトが更新されないと思います。

2023-12-27 09:04 UTC, sus-yoshikane-t commented on Tests/Scenes/Main.unity
NetworkObjectsProviderでNetwork Objectとしてシーン上のObjectを参照しているのには理由があるのでしょうか？(Spawn Failed ObjectはPrefabを使用しているようなので気になりました)

2023-12-27 09:24 UTC, mahaweilu commented on README.md
> +# Extreal.Integration.Multiplay.Common
全体的なことですが、Extreal.Integration.Multiplay.Messagingに変更後、関連する部分の修正（命名空間、アセンブリなど）お願いします。

2023-12-27 09:24 UTC, mahaweilu commented on Runtime/Extreal.Integration.Multiplay.Common.asmdef
> +        "Extreal.SampleApp.Holiday.Analyzer",
他のライブラリPRでも同様ですが、要らないと思います。

2023-12-27 09:24 UTC, mahaweilu commented on Runtime/INetworkObjectsProvider.cs
> +        /// <returns>GameObjects to be synchronized over the network.</returns>
ここに、具体的な型情報が欲しいと思います。GameObjects -> List<GameObject>

2023-12-27 09:24 UTC, mahaweilu commented on Runtime/MultiplayJoiningConfig.cs
> +        /// Messaging joining config.
Messaging -> Multiplay 他に同じようなところがないかを確認・修正お願いします。

2023-12-27 09:24 UTC, mahaweilu commented on Runtime/MultiplayJoiningConfig.cs
> +    public class MultiplayJoiningConfig
MultiplayMessagingConfigはどうですか？

2023-12-27 09:24 UTC, mahaweilu commented on Runtime/MultiplayUtil.cs
質問です。private methodにしなかった理由は何ですか？

2023-12-27 13:00 UTC, sasuke9410 requested changes

2023-12-27 13:00 UTC, sasuke9410 commented on Runtime/PlayerInput.cs
> +        public void SetMove(Vector2 newMoveDirection)
座標ではなく、移動方向を共有するためXZ座標のVector2型にしている認識です。
Holidayのような平面で移動する場合は問題ないと思いますが、
Web BURALITのような飛行(Y軸への移動)がある場合に対応できないのではないかと思いました。

2024-01-09 04:50 UTC, mahaweilu commented on Runtime/MultiplayUtil.cs
１．テスト側で使われやすい
２．internalにしたほうがよいかも

2024-01-09 04:56 UTC, mahaweilu commented on Tests/Scenes/Main.unity
converage問題があるかどうかを確認

2024-01-09 05:25 UTC, mahaweilu commented on Runtime/Extreal.Integration.Multiplay.Common.asmdef
> +        "Extreal.SampleApp.Holiday.Analyzer",
不要なので削除しました。
[e7543e6](https://github.com/extreal-dev/Extreal.Integration.Multiplay.Common/pull/2/commits/e7543e694e80e6f558bd0efe37eab6f78a5616d7)

2024-01-09 05:55 UTC, mahaweilu commented on Runtime/Extreal.Integration.Multiplay.Common.asmdef
> +        "Extreal.SampleApp.Holiday.Analyzer",
fixed [e7543e6](https://github.com/extreal-dev/Extreal.Integration.Multiplay.Messaging/pull/2/commits/e7543e694e80e6f558bd0efe37eab6f78a5616d7)

2024-01-09 06:00 UTC, mahaweilu commented on Runtime/MultiplayJoiningConfig.cs
> +    public class MultiplayJoiningConfig
以下と同じ理由で対応不要とします。
https://github.com/extreal-dev/Extreal.Integration.Messaging.Common/pull/1#discussion_r1445629865

2024-01-09 07:18 UTC, mahaweilu commented on Runtime/INetworkObjectsProvider.cs
> +        /// <returns>GameObjects to be synchronized over the network.</returns>
対応しました。以下からINetworkObjectsProvider.csの修正の確認お願いします。

[233f773](https://github.com/extreal-dev/Extreal.Integration.Multiplay.Messaging/pull/2/commits/233f773352a771097c33b56929beee59cae06a9e)

2024-01-09 07:19 UTC, mahaweilu commented on README.md
> +# Extreal.Integration.Multiplay.Common
対応しました。

[233f773](https://github.com/extreal-dev/Extreal.Integration.Multiplay.Messaging/pull/2/commits/233f773352a771097c33b56929beee59cae06a9e)

2024-01-09 07:20 UTC, mahaweilu commented on Runtime/MultiplayClient.cs
> +                if ((objectToBeUpdated.transform.position - networkObjectInfo.Position).sqrMagnitude > 0f)
対応しました。命名空間の変更コミットと一緒にしてしまいました。お手数ですが以下からMultiplayClient.csの修正の確認お願いします。

[233f773](https://github.com/extreal-dev/Extreal.Integration.Multiplay.Messaging/pull/2/commits/233f773352a771097c33b56929beee59cae06a9e)

2024-01-09 07:24 UTC, mahaweilu commented on Runtime/PlayerInput.cs
> +        public void SetMove(Vector2 newMoveDirection)
田口さんに確認しました。はい、その通りです。
>Web BURALITのような飛行(Y軸への移動)がある場合に

↑の場合に、アプリ側で「共有する情報」を追加する形で対応していただく想定です。イメージはガイドの以下のところです。

https://github.com/extreal-dev/Extreal.Guide/blob/feature/massively-multiplay/docs/integration/multiplay.messaging.md#%E5%90%8C%E6%9C%9F%E3%81%99%E3%82%8B%E3%83%97%E3%83%AC%E3%82%A4%E3%83%A4%E3%83%BC%E3%81%AE%E5%8B%95%E3%81%8D%E3%82%92%E8%BF%BD%E5%8A%A0%E3%81%99%E3%82%8B

2024-01-09 08:14 UTC, sus-yoshikane-t commented on Runtime/Extreal.Integration.Multiplay.Common.asmdef
> +        "Extreal.SampleApp.Holiday.Analyzer",
CIで検知できるようになっていて、マージ前に削除するそうなので、申し訳ありませんが元に戻していただくようお願いします。

2024-01-09 08:17 UTC, sus-yoshikane-t commented on Runtime/MultiplayClient.cs
> +                if ((objectToBeUpdated.transform.position - networkObjectInfo.Position).sqrMagnitude > 0f)
確認しました。

2024-01-09 08:49 UTC, mahaweilu commented on Runtime/Extreal.Integration.Multiplay.Common.asmdef
> +        "Extreal.SampleApp.Holiday.Analyzer",
CIで検知できるようになっていて、マージ前に削除するそうなので、"Extreal.Framework.Analyzer"を使うように戻しました。
[9560527](https://github.com/extreal-dev/Extreal.Integration.Multiplay.Messaging/pull/2/commits/956052788a96cf2538a7e7bf2e67e0c63ab7747f)

2024-01-09 09:15 UTC, sus-yoshikane-t commented on Tests/Scenes/Main.unity
分かりました。

2024-01-09 09:16 UTC, sus-yoshikane-t commented on Runtime/Extreal.Integration.Multiplay.Common.asmdef
> +        "Extreal.SampleApp.Holiday.Analyzer",
確認しました。

2024-01-16 11:09 UTC, kiyohome requested changes

2024-01-16 11:09 UTC, kiyohome commented on Runtime/MultiplayClient.cs
> +                var message = JsonUtility.ToJson(new MultiplayMessage(MultiplayMessageCommand.Update, networkObjectInfos: networkObjectInfosToSend.ToArray()));
MultiplayMessageにToJsonメソッド持たせたらダメですかね？
JsonUtility.ToJsonをいろんなとこで呼ばなくてもいいかと思いました。

2024-01-16 11:09 UTC, kiyohome commented on Runtime/MultiplayClient.cs
> +                var message = JsonUtility.ToJson(new MultiplayMessage(MultiplayMessageCommand.Update, networkObjectInfos: networkObjectInfosToSend.ToArray()));
FromJsonも合わせて、MultiplayMessageにまとめたらいいかと思います。

2024-01-16 11:09 UTC, kiyohome commented on Runtime/MultiplayUtil.cs
> +    public static class MultiplayUtil
ユーティリティクラスはUtilsの方がよくないでしょうか？

2024-01-16 11:09 UTC, kiyohome commented on Runtime/MultiplayUtil.cs
> +    public static class MultiplayUtil
このクラス、マルチプレイに関係ないユーティリティクラスで、かつアプリ開発で使えるのであれば、Core.Commonでもいいかと思いました。

2024-01-16 11:09 UTC, kiyohome commented on Runtime/NetworkClient.cs
> +        public string UserId { get; }
ClientIdだとダメでしょうか？クラス名と合ってないので違和感を感じました。

2024-01-16 11:09 UTC, kiyohome commented on Runtime/MultiplayMessage.cs
> +    public class MultiplayMessage
MultiplayMessageCommand
MultiplayMessage
NetworkClient
NetworkObjectInfo
これらのクラス名で、MutiplayとNetworkを付ける違いは何でしょうか？
Networkはネットワーク越しのリモートのClientやObjectを意味してますか？
あとObjectだけInfoを付けてるのに違和感あります。

2024-01-17 07:35 UTC, mahaweilu commented on Runtime/MultiplayClient.cs
> +                var message = JsonUtility.ToJson(new MultiplayMessage(MultiplayMessageCommand.Update, networkObjectInfos: networkObjectInfosToSend.ToArray()));
memo:
1.MultiplayMessageにToJsonメソッド：refactoring

2. PlayerInputValues: NetworkObjectInfoでtojson():利用者が使うので、利用者が使わないメソッドを追加しないほうが

2024-01-18 01:46 UTC, sus-yoshikane-t approved these changes

2024-01-18 05:25 UTC, mahaweilu commented on Runtime/MultiplayClient.cs
> +                var message = JsonUtility.ToJson(new MultiplayMessage(MultiplayMessageCommand.Update, networkObjectInfos: networkObjectInfosToSend.ToArray()));
>MultiplayMessageにToJsonメソッド持たせたらダメですかね？
>FromJsonも合わせて、MultiplayMessageにまとめたらいいかと思います。

MultiplayMessageにprivateメソッド化して対応します。

2024-01-18 05:26 UTC, mahaweilu commented on Runtime/MultiplayUtil.cs
> +    public static class MultiplayUtil
Utilsという命名に変え、Core.Commonに入れて対応します。

2024-01-18 05:26 UTC, mahaweilu commented on Runtime/MultiplayUtil.cs
> +    public static class MultiplayUtil
Utilsという命名に変え、Core.Commonに入れて対応します。

2024-01-18 05:29 UTC, mahaweilu commented on Runtime/MultiplayMessage.cs
> +    public class MultiplayMessage
>これらのクラス名で、MutiplayとNetworkを付ける違いは何でしょうか？
MutiplayはMutiplay用の意味合いです。

>Networkはネットワーク越しのリモートのClientやObjectを意味してますか？
はい、そうです。

2024-01-18 05:36 UTC, mahaweilu commented on Runtime/MultiplayMessage.cs
> +    public class MultiplayMessage
>あとObjectだけInfoを付けてるのに違和感あります。
NetworkClient.csのNetworkObjectsと区別してInfoを付けました。

以下の命名変更で対応します。
- NetworkClient.csのNetworkObjects --> NetworkPlayerGameObjects
- NetworkObjectInfo --> NetworkObjec

2024-01-18 05:45 UTC, mahaweilu commented on Runtime/NetworkClient.cs
> +        public string UserId { get; }
MessagingClientのUserIdと同じもので「このクライアントのユーザを区別する」識別子でこのままで良いと思いますがどうですか？

2024-01-18 09:10 UTC, mahaweilu commented on Runtime/MultiplayUtil.cs
> +    public static class MultiplayUtil
方針：
・prefabのnameで識別するように修正
　・dicに各nameをいれる
　・Utilsが要らなくなる

2024-01-18 09:12 UTC, mahaweilu commented on Runtime/NetworkClient.cs
> +        public string UserId { get; }
ClientId

2024-01-23 08:47 UTC, mahaweilu commented on Runtime/MultiplayUtil.cs
> +    public static class MultiplayUtil
利用者側に識別子を指定していただくため、MultiplayUtil.csを削除して対応しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.Messaging/pull/2/commits/f6dd8dad242ab6658cd2ef0707e8fbc284c621d3

自動テストも変更に応じて修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.Messaging/pull/2/commits/48834e31f1c0440038c85ad289e9e47661d489f4

https://github.com/extreal-dev/Extreal.Integration.Multiplay.Messaging/pull/2/commits/9d68333c081ba8cee76b5d27d3ef7156ffda1d92

2024-01-23 08:50 UTC, mahaweilu commented on Runtime/NetworkClient.cs
> +        public string UserId { get; }
Multiplay.Messaging内で「UserId関連」を修正しました。
[6dfaeb3](https://github.com/extreal-dev/Extreal.Integration.Multiplay.Messaging/pull/2/commits/6dfaeb32744c772bb0e57ed27a32440f4f54b28c)

Messaging

Messaging.Redis

2024-01-23 09:11 UTC, mahaweilu commented on Runtime/MultiplayMessage.cs
> +    public class MultiplayMessage
「NetworkObjectInfo --> NetworkObject」クラス名を変更して対応しました。
[f6dd8da](https://github.com/extreal-dev/Extreal.Integration.Multiplay.Messaging/pull/2/commits/f6dd8dad242ab6658cd2ef0707e8fbc284c621d3)

2024-01-23 09:13 UTC, mahaweilu commented on Runtime/MultiplayClient.cs
> +                var message = JsonUtility.ToJson(new MultiplayMessage(MultiplayMessageCommand.Update, networkObjectInfos: networkObjectInfosToSend.ToArray()));
対応しました。以下MultiplayMessage.csとMultiplayClient.csから確認お願いします。
[f6dd8da](https://github.com/extreal-dev/Extreal.Integration.Multiplay.Messaging/pull/2/commits/f6dd8dad242ab6658cd2ef0707e8fbc284c621d3)

2024-01-24 06:12 UTC, mahaweilu commented on Runtime/MultiplayClient.cs
> +                var message = JsonUtility.ToJson(new MultiplayMessage(MultiplayMessageCommand.Update, networkObjectInfos: networkObjectInfosToSend.ToArray()));
[5f728ef](https://github.com/extreal-dev/Extreal.Integration.Multiplay.Messaging/pull/2/commits/5f728ef1be27b2aee11f17eb82f43e8f4741c26e)

[53ba7da](https://github.com/extreal-dev/Extreal.Integration.Multiplay.Messaging/pull/2/commits/53ba7daaf8a747b29a7d34d8c777810c5504bb64)

2024-01-31 08:14 UTC, sus-taguchi-t commented on Runtime/MultiplayUtil.cs
> +    public static class MultiplayUtil
https://github.com/extreal-dev/Extreal.Integration.Multiplay.Messaging/pull/2#discussion_r1456916672
こちらと同様です。

2024-01-31 09:09 UTC, sus-taguchi-t commented on Runtime/MultiplayMessage.cs
> +    public class MultiplayMessage
各メンバもリネームしました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.Messaging/pull/2/commits/f246fa65e845e20e06764abdafe102851475bad1

2024-01-31 09:30 UTC, sus-taguchi-t commented on Runtime/MultiplayClient.cs
> +                    }
[性能テストで検知したタイミング問題](https://github.com/orgs/extreal-dev/projects/1/views/1?pane=issue&itemId=50393425)」について以下で追加対応しました。
「ObjectSpawn のメッセージが飛んできたときに joinedClients にユーザが追加されていない場合は追加する」ように修正しています。
[5f728ef](https://github.com/extreal-dev/Extreal.Integration.Multiplay.Messaging/pull/2/commits/5f728ef1be27b2aee11f17eb82f43e8f4741c26e)

[53ba7da](https://github.com/extreal-dev/Extreal.Integration.Multiplay.Messaging/pull/2/commits/53ba7daaf8a747b29a7d34d8c777810c5504bb64)

2024-01-31 09:30 UTC, sus-taguchi-t commented on Runtime/MultiplayClient.cs
> +        protected virtual void SynchronizeLocal()
性能テスト時にオーバーライドできるように virtual 指定しています。
またこのメソッドから参照できるメンバも protected にしています。

2024-01-31 09:30 UTC, sus-taguchi-t commented on Runtime/MultiplayClient.cs
> +            }
同期時に補間・予測をするように修正しました。

2024-01-31 09:30 UTC, sus-taguchi-t commented on Runtime/JsonConverter.cs
Vector3 等の構造体をシリアライズ/デシリアライズする際に必要なコンバータを定義しています。
これらは `Extreal.Core.Common` に移植した方が良いかもしれません。

2024-01-31 09:30 UTC, sus-taguchi-t commented on Runtime/MultiplayMessage.cs
JSON にシリアライズ/デシリアライズする方法を JsonConvert を使用する形に修正しました。
その際 `OnBeforeSerialize` と `OnAfterDeserialize` は自動で呼ばれないので手動で呼んでいます。

2024-02-02 08:45 UTC, sus-taguchi-t commented on Runtime/MultiplayClient.cs
> +        protected virtual void SynchronizeLocal()
protected プロパティはゲッターを作成する

2024-02-02 09:03 UTC, sus-taguchi-t commented on Runtime/JsonConverter.cs
Common に移動してこれを使用するように変える（？）
バックログに積む

2024-02-02 09:07 UTC, sus-taguchi-t commented on Runtime/MultiplayMessage.cs
インターフェースは削除する

2024-02-02 09:09 UTC, kiyohome approved these changes

2024-02-02 09:54 UTC, sus-taguchi-t commented on Runtime/MultiplayClient.cs
> +        protected virtual void SynchronizeLocal()
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.Messaging/pull/2/commits/8d26edcec3408ee9697e51fd9b88d2f64702ec4f

2024-02-02 10:06 UTC, sus-taguchi-t commented on Runtime/MultiplayMessage.cs
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.Messaging/pull/2/commits/33791a371b97ca410c5a652faf1c59c6705cbd3e

2024-02-02 10:09 UTC, sus-taguchi-t commented on Runtime/JsonConverter.cs
積みました。
https://github.com/orgs/extreal-dev/projects/1/views/1?pane=issue&itemId=52008872

2024-02-05 05:36 UTC, sasuke9410 approved these changes

2024-02-05 06:05 UTC, merged